version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  slack: circleci/slack@4.4.2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.1
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: version
          command: bundle -v
      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
      - ruby/install-deps
      - ruby/rubocop-check
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  main:
    jobs:
      - build:
          context:
            - slack
